font_size 15
font_family JetBrainsMono Nerd Font
shell /usr/bin/zsh
background_opacity 0.90
confirm_os_window_close 0

cursor_shape beam
cursor_blink_interval 0.5

enable_audio_bell no

window_padding_width 10

tab_bar_edge top
tab_bar_style powerline
include current-theme.conf
mouse_hide_wait 2.0
cursor_trail 1
repaint_delay 10
input_delay 3
sync_to_monitor yes
